name: engineering workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Check if requirements.txt exists
        run: |
          if [ ! -f requirements.txt ]; then
            echo "requirements.txt no encontrado. Asegúrate de que el archivo esté presente."
            exit 1
          fi

      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # Si tienes un archivo de requisitos

      - name: Run tests
        run: |
          pytest  # Ejecutar todas las pruebas con pytest

